CREATE TABLE envios (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at               TIMESTAMP(6) WITHOUT TIME ZONE,
    destino                  VARCHAR(255),
    fecha_estimada_entrega   TIMESTAMP(6) WITHOUT TIME ZONE,
    guia_despecho            VARCHAR(255),
    pedido_id                BIGINT NOT NULL,
    ruta_descripcion         VARCHAR(255),
    status                   VARCHAR(255) NOT NULL,
    tipo_envio               VARCHAR(255) NOT NULL,
    transportista            VARCHAR(255),
    CONSTRAINT envios_pkey PRIMARY KEY (id)
);
