server.port=8082
spring.application.name=ms-inventario

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:inventario_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info,metrics
