CREATE TABLE pedidos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cantidad        INTEGER,
    cliente_nombre  VARCHAR(255),
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    destino         VARCHAR(255),
    observaciones   VARCHAR(255),
    producto_id     BIGINT,
    status          VARCHAR(255) NOT NULL,
    tipo_pedido     VARCHAR(255) NOT NULL,
    total           DOUBLE PRECISION NOT NULL,
    user_email      VARCHAR(255),
    user_id         BIGINT NOT NULL,
    CONSTRAINT pedidos_pkey PRIMARY KEY (id)
);

CREATE TABLE saga_estado (
    saga_id          UUID NOT NULL,
    actualizado_en   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    creado_en        TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    envio_id         BIGINT,
    estado           VARCHAR(20) NOT NULL,
    paso_actual      VARCHAR(50) NOT NULL,
    payload          JSONB NOT NULL,
    pedido_id        BIGINT,
    stock_reservado  BOOLEAN NOT NULL,
    tipo             VARCHAR(50) NOT NULL,
    ultimo_error     TEXT,
    CONSTRAINT saga_estado_pkey PRIMARY KEY (saga_id),
    CONSTRAINT saga_estado_estado_check CHECK (estado IN ('INICIADA','EN_PROGRESO','COMPLETADA','COMPENSANDO','FALLIDA'))
);
