CREATE TABLE productos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bodega           VARCHAR(255),
    descripcion      VARCHAR(255),
    nombre           VARCHAR(255) NOT NULL,
    precio_unitario  DOUBLE PRECISION NOT NULL,
    sku              VARCHAR(255) NOT NULL,
    stock_actual     INTEGER NOT NULL,
    umbral_minimo    INTEGER NOT NULL,
    CONSTRAINT productos_pkey PRIMARY KEY (id),
    CONSTRAINT uk8bwvjlh8b1xi4cc4ar819q61y UNIQUE (sku),
    CONSTRAINT productos_stock_actual_check CHECK (stock_actual >= 0),
    CONSTRAINT productos_umbral_minimo_check CHECK (umbral_minimo >= 0)
);
