server.port=8083
spring.application.name=ms-pedidos

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:pedidos_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info,metrics

# Circuit Breaker (Resilience4j)
resilience4j.circuitbreaker.instances.inventario.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventario.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventario.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.inventario.permitted-calls-in-half-open-state=3

inventario.service.url=http://ms-inventario:8082
