CREATE TABLE users (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cancelacion_completada_en   TIMESTAMP(6) WITHOUT TIME ZONE,
    cancelacion_solicitada_en   TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at                  TIMESTAMP(6) WITHOUT TIME ZONE,
    email                       VARCHAR(255) NOT NULL,
    oposicion_procesamiento     BOOLEAN,
    oposicion_registrada_en     TIMESTAMP(6) WITHOUT TIME ZONE,
    password                    VARCHAR(255) NOT NULL,
    role                        VARCHAR(255),
    status                      VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);
