server.port=8080
spring.application.name=api-gateway

# ── Rutas del Gateway (MVC mode) ──
spring.cloud.gateway.mvc.routes[0].id=auth-public
spring.cloud.gateway.mvc.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[1].id=product-service
spring.cloud.gateway.mvc.routes[1].uri=http://product-service:8082
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=2

spring.cloud.gateway.mvc.routes[2].id=order-service
spring.cloud.gateway.mvc.routes[2].uri=http://order-service:8083
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.mvc.routes[2].filters[0]=StripPrefix=2

# JWT (para el AuthFilter que crearemos en Fase 2)
jwt.secret=${JWT_SECRET:default_dev_secret_32_chars_min}

# Actuator
management.endpoints.web.exposure.include=health,info
