CREATE TABLE pagos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    commerce_order   VARCHAR(255) NOT NULL,
    confirmado_en    TIMESTAMP(6) WITHOUT TIME ZONE,
    creado_en        TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    email            VARCHAR(255),
    estado           VARCHAR(255) NOT NULL,
    flow_order       BIGINT,
    flow_token       VARCHAR(255),
    monto            DOUBLE PRECISION,
    pedido_id        BIGINT NOT NULL,
    url_pago         VARCHAR(255),
    CONSTRAINT pagos_pkey PRIMARY KEY (id),
    CONSTRAINT uki00kqwtk8bsukmuckeu0ywxts UNIQUE (commerce_order),
    CONSTRAINT pagos_estado_check CHECK (estado IN ('INICIADO','PENDIENTE','PAGADO','RECHAZADO','ANULADO'))
);
